### ISSUE TITLE
LIRA DEX Home

### ISSUE THREAD

**Issue by n0x0ver** [lira-dao/ecosystem#13]
Description:

Request for the creation of the LIRA DEX home page as per the UI/UX design, composed as follows:

General Structure:

A main card that occupies the entire page.
The main card is divided into sections.
Each section contains other cards that display specific graphs or data.
Detailed Sections:

Welcome to LIRA DEX:

A set of cards displaying:
TVL (Total Value Locked)
Total volume on the DEX
Total LDT in staking for reward boosting
A small chart of the price of LDT, LIRA, TBB, TBS, and TBG
TOP Tokens:

A carousel of small cards showing the ranking of tokens with the highest price increase.
Main Functions of the DEX:

Section with call to action for the main functions of the DEX:
Swap
Farm
Add Liquidity
Staking
Top Farms:

A carousel of cards representing the ranking of farm pools with the highest rewards.
Top Pools:

A carousel of cards representing the ranking of pools by TVL.
Top Tokens:

A carousel of cards representing the ranking of tokens by transaction volume.
This structure should ensure an informative and intuitive user interface for LIRA DEX users, as per the UI/UX design. Thank you for your attention and I look forward to your feedback.

**Comment by fredev** [comment]
this issue will be closed and splitted in multiple issues
