### ISSUE TITLE
Creation of the "MY Portfolio" Page on Our DEX Platform

### ISSUE THREAD

**Issue by n0x0ver** [lira-dao/ecosystem#27]
Description: We need to develop the "MY Portfolio" page for our online DEX platform. This page will allow users to view and manage their digital assets.

Required Features:

- Asset Visualization: The page should display a list of all assets owned by the user, including name, symbol, quantity, and current value.

- Total Portfolio Value: Show the total value of the user's portfolio, calculated by summing the current values of all assets.

- Charts and Statistics: Include charts showing asset distribution and performance over time.

- Filters and Sorting: Allow users to filter and sort assets by various criteria (e.g., by name, value, quantity).

- Asset Details: When an asset is selected, display additional details such as transaction history, performance charts, and specific asset information.

- Wallet Interaction: Implement the ability to connect the user's wallet to import and sync assets.

User Interface: The UI should be user-friendly and responsive, compatible with different devices (desktop, tablet, mobile).

Additional Sections:

- Owned Liquidity: Display the liquidity pools in which the user has invested, including the value of liquidity and the percentage of the pool owned.

- Farming Rewards: Show rewards obtained from liquidity mining activities, detailing the current value of rewards and their history.

- Staking Rewards: Display rewards from staking, including key metrics like total staked, APY (Annual Percentage Yield), and cumulative rewards.

References

- Reference : Design UI/UX

**Comment by fredev** [comment]
this issue will be closed and splitted in multiple issues
