### ISSUE TITLE
add prices in usd

### ISSUE THREAD

**Issue by nicholas1990** [lira-dao/ecosystem#30]
Swap Page. Add prices in usd form coinmarketcap source

**Comment by nicholas1990** [comment]
Solved: 
footer UI issue, coinmarketcap prices
- [ x ] replace 'powered by' with 'prices by'
- [ x ] text should go to the bottom right of the page
- [ x ] the text must be dark gray in color and with a smaller font size
- [ x ] remove the underline from the link

**Comment by silvertoml** [comment]
I think you can close the current issue.

**Comment by silvertoml** [comment]
![image](https://github.com/lira-dao/ecosystem/assets/168391793/b9b00136-477b-496f-8b40-10d309d13b7c)

**Comment by silvertoml** [comment]
![image](https://github.com/lira-dao/ecosystem/assets/168391793/54cfd583-9749-49fe-a297-1530ded94728)

**Comment by silvertoml** [comment]
are there other items for this issue ?
