### ISSUE TITLE
[dex] footer must be at to the bottom of the page

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#33]
The footer must be at the bottom of the page on desktop

On mobile the footer must not be fixed but follow the content with 

![Screenshot 2024-07-09 alle 13 55 49](https://github.com/lira-dao/ecosystem/assets/5547669/ec233dcf-a85e-46d8-a3fa-1af0f90d43dc)

![Screenshot 2024-07-09 alle 14 07 47](https://github.com/lira-dao/ecosystem/assets/5547669/f75dcc35-e198-4f25-894c-1c2e2d94aec0)

**Comment by nicholas1990** [comment]
In branch 'feature/30-add-prices-in-usd' this issues is solved.
![Screenshot from 2024-07-09 17-29-53](https://github.com/lira-dao/ecosystem/assets/13333845/ed965104-0bc4-4703-866a-4cf415c9ecf4)

**Comment by fredev** [comment]
ok, let's put the text on a single line and further reduce the font size

furthermore, the pages must have a lower border that exceeds the height of the footer otherwise the components that end up below it cannot be clicked
