### ISSUE TITLE
[apps] add to metamask button does not work on mobile

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#34]
The 'add to metamask' buttons do not work on mobile in both web applications

Bounty: 1000 LDT

**Comment by Emmanueltech** [comment]
Hi I would like to work on this task

**Comment by fredev** [comment]
@Emmanueltech this issue has been under investigation by @silvertoml please join our discord at https://discord.gg/fDRBajCB9V so we can talk about it

**Comment by Emmanueltech** [comment]
Roger that.

**Comment by silvertoml** [comment]
> Roger that.

now i am discussing with metamask team
