### ISSUE TITLE
[dex] refactor amount inputs with CurrencyInput component

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#35]
refactor inputs related to amounts with `CurrencyInput`component in all pages

Pages with old implementation:
- apps/dex/src/pages/RemoveLiquidity.tsx
- apps/dex/src/pages/Stake.tsx
- apps/dex/src/pages/TreasuryMint.tsx
- apps/dex/src/pages/Unstake.tsx

**Comment by Emmanueltech** [comment]
Hi @fredev I would like to work on this.

**Comment by fredev** [comment]
@Emmanueltech sure
