### ISSUE TITLE
[dex] add footer social icons

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#44]
social icons must be present in the footer of the dex site

- twitter: https://twitter.com/LIRA_DAO
- discord: https://discord.gg/fDRBajCB9V
- telegram: https://t.me/LIRA_DAO

Reward: 150 LDT

**Comment by dev0614** [comment]
Good!

Checked the repo and code and suggest that convert to vite or next project.

**Comment by fredev** [comment]
The comment is not related to the issue, I have opened a new issue to continue the discussion #45

**Comment by dev0614** [comment]
I added social icons to footer
and am about to push the code, but there is permission issue.
tbh, I don't wanna fork the repo, since the code style is not suit to my github 😁 
can you give me permission?

**Comment by fredev** [comment]
Permission granted, what is wrong with the code style? 

I'll check the turborepo config, thanks
