### ISSUE TITLE
[dex-web] switching to vue or next

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#45]
With this issue we want to evaluate switching to vue or next

I would like to discuss the following points:

- advantages and disadvantages of vue and next compared to the current implementation
- quantify the time needed for the refactor separately for the main website and for the dex website

Based on the result of this discussion it will be decided whether to carry out the refactor and which framework to use

**Comment by dev0614** [comment]
This is my opinion about _**Vue.js**_ and _**Next.js**_.
It's up to you to decide which framework to use.

**1. Vue.js**

> - Easier learning curve compared to React
> - Better performance for smaller applications
> - Smaller ecosystem compared to React
> - Less suitable for very large-scale applications

**2. Next.js**

> - Built on top of React, so existing React knowledge is transferable
> - Server-side rendering out of the box
> - Automatic code splitting
> - Built-in routing. _e.g. There is page and app routing and built-in routing, so you don't need to handle the router._
> - Better SEO capabilities
> - Steeper learning curve for developers not familiar with server-side rendering
> - May be overkill for simple applications. _e.g. Simple Landing Page_
> - Some limitations in routing compared to client-side routing libraries. _e.g. react-apexcharts, some slide modules_

**3. Time Estimation**

No matter which framework you choose, it's likely to take at least a month to refactor.

**Comment by fredev** [comment]
I think that next is the optimal solution, unfortunately the proposed one month time frame is prohibitive for opening a bounty, we could address the issue when we have the funds available to hire a developer

I leave the issue open for further opinions on the matter
