### ISSUE TITLE
[dex] implement max slippage on swap page

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#46]
We want to implement an input to give the user the possibility to change the maximum slippage when making a swap

it is requested:

- set the default slippage to 0.5%
- between the swap form and the prices implement an information text and an input in which to display the current slippage
- the input must be editable between the values ​​0 and 100 with a decimal precision of 1
- the correct slippage value must be set in the transaction (amountOutMin)
- add an information text that displays the minimum output of the swap

Reward: 500 LDT

**Comment by dev0614** [comment]
Pls check.
