### ISSUE TITLE
[dex] get all referrals

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#60]
Expand the get referral call with the total count of the three referral levels

For the first level we calculate the number of referrals registered directly from the address present in the path parameter

For the second level we count all the referrals made by the first level referrals

The same goes for the third level but using the referrals from the second level

method: GET
path: /referrals/:address

**Comment by nicholas-aternum** [comment]
It's ok?
![Screenshot from 2024-08-20 17-25-46](https://github.com/user-attachments/assets/aa1612cb-0820-4141-8166-e6ccb21288e0)
