### ISSUE TITLE
[dex] intercept stake event for referral bonus

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#62]
Intercept staking events on time lock staking pools

If the wallet staking for the first time has been referred, a reward equal to 10% of the value staked must be assigned to both the staking wallet and the referrer

The rewards must be saved in a postgres table to be subsequently sent with the following data

- address that performed the stake
- staked amount
- reward amount
- transaction id of the staking event
- transaction id of the rewards sending

**Comment by nicholas-aternum** [comment]
I added the address of the staked token to the basic specifications, because the reward will be sent in that currency.
