### ISSUE TITLE
[dex] send referral bonus

### ISSUE THREAD

**Issue by fredev** [lira-dao/ecosystem#63]
The reward send transaction must be done using multicall

https://docs.arbitrum.io/build-decentralized-apps/reference/useful-addresses

arbitrum sepolia
https://sepolia.arbiscan.io/address/0xA115146782b7143fAdB3065D86eACB54c169d092

abitrum one
https://arbiscan.io/address/0x842eC2c7D803033Edf55E478F461FC547Bc54EB2

**Comment by nicholas-aternum** [comment]
It's ok. An example of rewards sended using multicall is:
https://sepolia.arbiscan.io/tx/0x5583a36080d1a83a7886857bfa2bd79728d1ced3255836e1cc0ecacaaa36bf59
